---
driver:
  name: docker
  hostname: helm.kitchen.local
  use_sudo: false

platforms:
  - name: ubuntu-xenial
    driver_config:
      image: 'trevorj/salty-whales:xenial'
      platform: ubuntu

provisioner:
  name: salt_solo
  log_level: info
  require_chef: false
  formula: chartmuseum
  salt_version: 2016.11.8
  salt_bootstrap_options: -U -p python-git stable 2016.11.8
  dependencies:
    - name: helm
      repo: git
      source: https://github.com/tmeneau/salt-formula-helm.git
  state_top:
    base:
      '*':
        - helm
        - chartmuseum.packages_updated

verifier:
  name: inspec
  sudo: true

suites:
  - name: docker
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - chartmuseum
              - helm
        helm.sls:
          helm:
            tiller:
              install: false
            kubectl:
              install: false
        chartmuseum.sls:
          chartmuseum:
            bind_ip: 0.0.0.0
            public_url: http://0.0.0.0
            git:
              repos:
                - url: https://github.com/kubernetes/charts.git
                  subpath: stable/mailhog
                - url: https://github.com/kubernetes/charts.git
                  subpath: stable/redmine