---
driver:
  name: docker
  hostname: helm.kitchen.local
  use_sudo: false

platforms:
  - name: ubuntu-xenial
    driver_config:
      image: 'trevorj/salty-whales:xenial'
      platform: ubuntu
      privileged: true
      volume:
        #
        # Mount the docker sock so that the Kitchen test container has 
        # access to the host's docker process. Note that this does add an
        # element of complication since docker is being run using the host's
        # docker server, not the kitchen container's docker server.
        # 
        # For example, and containers created will be *siblings* of the 
        # Kitchen test container, not children; any volumes mounted to the
        # created container will be mounted *from the host*, not the Kitchen
        # container.
        # 
        # Hence using the data volume, which can be mounted at the appropriate
        # path(s) for both the Kitchen container, and any containers created
        # by the formula under test.
        #
        - /var/run/docker.sock:/var/run/docker.sock
        - chartmuseumformula_data:/datavols/helm/chart-repo

provisioner:
  name: salt_solo
  log_level: info
  require_chef: false
  formula: chartmuseum
  salt_version: 2016.11.8
  salt_bootstrap_options: -U -p python-git stable 2016.11.8
  dependencies:
    - name: pip
      repo: git
      source: https://github.com/xetus-oss/pip-formula.git
    - name: docker
      repo: git
      source: https://github.com/saltstack-formulas/docker-formula.git
    - name: helm
      repo: git
      source: https://github.com/tmeneau/salt-formula-helm.git
  state_top:
    base:
      '*':
        - helm
        - pip.installed
        - docker
        - chartmuseum

verifier:
  name: inspec
  sudo: true

suites:
  - name: chartmuseum
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - chartmuseum
              - helm
              - docker
        docker.sls:
          docker:
            install_docker_py: true
        helm.sls:
          helm:
            tiller:
              install: false
            kubectl:
              install: false
        chartmuseum.sls:
          chartmuseum:
            bind_ip: 0.0.0.0
            public_url: http://0.0.0.0
            data_volume: 
              name: chartmuseumformula_data
            git:
              repos:
                - url: https://github.com/kubernetes/charts.git
                  subpath: stable/mailhog
                - url: https://github.com/kubernetes/charts.git
                  subpath: stable/redmine